const VEHICLES = [
  {
    "id": "cobra-scorpion",
    "name": "Cobra Scorpion",
    "fullName": "Cobra Scorpion Desert Attack Vehicle",
    "affiliation": "Cobra",
    "vehicleType": "Desert Attack ATV",
    "firstYear": "1994",
    "crew": "1",
    "armament": "Mounted gun",
    "packagedWith": null,
    "bio": "A Battle Corps-era desert attack ATV, the Scorpion let Cobra troops strike fast across open desert terrain before withdrawing out of range.",
    "image": "images/cobrascorpion.jpg"
  },
  {
    "id": "ghoststriker-x16",
    "name": "Ghoststriker X-16",
    "fullName": "Ghoststriker X-16 Combat Jet",
    "affiliation": "G.I. Joe",
    "vehicleType": "Combat Jet",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Wing-mounted missiles",
    "packagedWith": "Ace",
    "bio": "Piloted by the veteran flier Ace, the Ghoststriker X-16 was a Battle Corps combat jet built for fast strikes deep into Cobra-held airspace.",
    "image": "images/ghoststriker.jpg"
  },
  {
    "id": "cobra-ice-snake",
    "name": "Cobra Ice Snake",
    "fullName": "Cobra Ice Snake Arctic Attack Vehicle",
    "affiliation": "Cobra",
    "vehicleType": "Arctic Attack Vehicle",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "A Cobra arctic attack vehicle built to operate in frozen terrain, the Ice Snake let Cobra press its offensive into the coldest corners of the map.",
    "image": "images/cobraicesnake.jpg"
  },
  {
    "id": "mudbuster",
    "name": "Mudbuster",
    "fullName": "Mudbuster All-Terrain Battle Truck",
    "affiliation": "G.I. Joe",
    "vehicleType": "All-Terrain Battle Truck",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Mounted gun",
    "packagedWith": "Cross-Country",
    "bio": "Driven by the transport specialist Cross-Country, the Mudbuster was an all-terrain Battle Corps truck built to haul troops and gear through the worst terrain Cobra could throw at it.",
    "image": "images/mudbuster.jpg"
  },
  {
    "id": "shark-9000",
    "name": "Shark 9000",
    "fullName": "Shark 9000",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Boat",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Missile launcher",
    "packagedWith": "Cutter",
    "bio": "Piloted by the Coast Guard veteran Cutter, the Shark 9000 was a Battle Corps attack boat built for fast coastal strikes and search-and-destroy runs.",
    "image": "images/shark9000.jpg"
  },
  {
    "id": "monster-blaster-apc",
    "name": "Monster Blaster A.P.C.",
    "fullName": "Monster Blaster Armored Personnel Carrier",
    "affiliation": "G.I. Joe",
    "vehicleType": "Armored Personnel Carrier",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Twin cannons",
    "packagedWith": "Clutch",
    "bio": "Driven by Clutch, the Monster Blaster A.P.C. was a hulking armored personnel carrier from the Mega Marines assortment, built to haul troops through heavy resistance.",
    "image": "images/monsterblasterapc.jpg"
  },
  {
    "id": "ninja-lightning",
    "name": "Ninja Lightning",
    "fullName": "Ninja Lightning Fast Attack Cycle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Motorcycle",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Missile launcher",
    "packagedWith": null,
    "bio": "A fast attack motorcycle from the Ninja Force assortment, the Ninja Lightning let the team's ninja operatives close on Cobra targets at speed.",
    "image": "images/ninja-lightning.jpg"
  },
  {
    "id": "starfighter",
    "name": "Starfighter",
    "fullName": "Star Brigade Starfighter",
    "affiliation": "G.I. Joe",
    "vehicleType": "Spacecraft",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Laser cannons",
    "packagedWith": "Sci-Fi",
    "bio": "Flown by the laser-rifle specialist Sci-Fi, the Starfighter was the G.I. Joe Star Brigade's own spacecraft, built for the team's push into orbital and off-world combat.",
    "image": "images/starfighter.jpg"
  },
  {
    "id": "cobra-invader",
    "name": "Cobra Invader",
    "fullName": "Star Brigade Cobra Invader",
    "affiliation": "Cobra",
    "vehicleType": "Spacecraft",
    "firstYear": "1993",
    "crew": "1",
    "armament": "Laser cannons",
    "packagedWith": null,
    "bio": "Cobra's answer to the G.I. Joe Star Brigade, the Invader was a spacecraft built to carry Cobra's fight into orbit and beyond.",
    "image": "images/cobrainvader.jpg"
  },
  {
    "id": "cobra-earthquake",
    "name": "Cobra Earthquake",
    "fullName": "Cobra Earthquake Construction Combat Vehicle",
    "affiliation": "Cobra",
    "vehicleType": "Construction Combat Vehicle",
    "firstYear": "1992",
    "crew": "1",
    "armament": "Wrecking claw, mounted cannon",
    "packagedWith": null,
    "bio": "A repurposed construction rig turned combat vehicle, the Earthquake let Cobra flatten G.I. Joe defenses with its crushing claw and mounted firepower.",
    "image": "images/cobraearthquake.jpg"
  },
  {
    "id": "cobra-parasite",
    "name": "Cobra Parasite",
    "fullName": "Cobra Parasite",
    "affiliation": "Cobra",
    "vehicleType": "Walker Vehicle",
    "firstYear": "1992",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "A spindly, insect-like walker, the Parasite let Cobra troops cross rough terrain other vehicles couldn't while bringing firepower along with them.",
    "image": "images/cobraparasite.jpg"
  },
  {
    "id": "patriot",
    "name": "Patriot",
    "fullName": "Patriot Armored Missile Launcher Transport",
    "affiliation": "G.I. Joe",
    "vehicleType": "Armored Missile Transport",
    "firstYear": "1992",
    "crew": "1",
    "armament": "Missile launcher",
    "packagedWith": null,
    "bio": "An armored missile transport, the Patriot let the G.I. Joe team move heavy long-range firepower quickly to wherever the front line shifted.",
    "image": "images/patriot.jpg"
  },
  {
    "id": "cobra-rat",
    "name": "Cobra Rat",
    "fullName": "Cobra Rat",
    "affiliation": "Cobra",
    "vehicleType": "Scout Vehicle",
    "firstYear": "1992",
    "crew": "1",
    "armament": "Mounted gun",
    "packagedWith": null,
    "bio": "A low, rodent-shaped Cobra scout vehicle, the Rat crept through cover to feed enemy positions back to Cobra command.",
    "image": "images/cobrarat.jpg"
  },
  {
    "id": "storm-eagle",
    "name": "Storm Eagle",
    "fullName": "Storm Eagle Tactical Fighter Jet",
    "affiliation": "G.I. Joe",
    "vehicleType": "Fighter Jet",
    "firstYear": "1992",
    "crew": "1",
    "armament": "Wing-mounted missiles",
    "packagedWith": null,
    "bio": "A sleek tactical fighter jet, the Storm Eagle gave the G.I. Joe team fast air superiority against Cobra aircraft.",
    "image": "images/stormeagle.jpg"
  },
  {
    "id": "cobra-eco-striker",
    "name": "Cobra Eco Striker",
    "fullName": "Cobra Eco Striker",
    "affiliation": "Cobra",
    "vehicleType": "All-Terrain Attack Vehicle",
    "firstYear": "1992",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "Part of the environmentally themed Eco-Warriors line, the Cobra Eco Striker was an all-terrain attack vehicle used by Cobra's Eco-Warriors adversaries to spread toxic damage.",
    "image": "images/cobraecostriker.jpg"
  },
  {
    "id": "desert-apache",
    "name": "Desert Apache",
    "fullName": "AH-74 Desert Apache",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Helicopter",
    "firstYear": "1992",
    "crew": "1",
    "armament": "Nose-mounted gun, rocket pods",
    "packagedWith": null,
    "bio": "Part of the sound-effect-equipped Sonic Fighters line, the AH-74 Desert Apache was an attack helicopter that played engine and weapon sounds as it flew missions for the G.I. Joe team.",
    "image": "images/desertapache.jpg"
  },
  {
    "id": "attack-cruiser",
    "name": "Attack Cruiser",
    "fullName": "Attack Cruiser",
    "affiliation": "G.I. Joe",
    "vehicleType": "Heavy Tank",
    "firstYear": "1991",
    "crew": "1",
    "armament": "Elevating cannon",
    "packagedWith": null,
    "bio": "A heavily armored G.I. Joe tank, the Attack Cruiser brought concentrated firepower to bear against Cobra armor and fortified positions alike.",
    "image": "images/attackcruiser.jpg"
  },
  {
    "id": "battle-wagon",
    "name": "Battle Wagon",
    "fullName": "Motorized Battle Wagon",
    "affiliation": "G.I. Joe",
    "vehicleType": "Motorized Tank",
    "firstYear": "1991",
    "crew": "2",
    "armament": "Rotating turret cannon, side-mounted gun",
    "packagedWith": null,
    "bio": "A motorized tracked tank with a battery-powered drive system, the Battle Wagon let the G.I. Joe team roll into combat under real powered motion.",
    "image": "images/battlewagon.jpg"
  },
  {
    "id": "brawler",
    "name": "Brawler",
    "fullName": "Brawler Tank",
    "affiliation": "G.I. Joe",
    "vehicleType": "Combat Tank",
    "firstYear": "1991",
    "crew": "1",
    "armament": "Missile launcher",
    "packagedWith": null,
    "bio": "A compact, heavily armed G.I. Joe combat tank, the Brawler was built to slug it out with Cobra armor at close range.",
    "image": "images/brawler.jpg"
  },
  {
    "id": "cobra-paralyzer",
    "name": "Cobra Paralyzer",
    "fullName": "Cobra Paralyzer",
    "affiliation": "Cobra",
    "vehicleType": "Assault Tank",
    "firstYear": "1991",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "A Cobra assault tank built late in the toy line's run, the Paralyzer gave Cobra ground troops another heavily armed vehicle to push back G.I. Joe advances.",
    "image": "images/cobraparalyzer.jpg"
  },
  {
    "id": "septic-tank",
    "name": "Septic Tank",
    "fullName": "Eco-Warriors Septic Tank",
    "affiliation": "Cobra",
    "vehicleType": "Toxic Waste Tank",
    "firstYear": "1991",
    "crew": "1",
    "armament": "Toxic sludge cannon",
    "packagedWith": null,
    "bio": "Part of the environmentally themed Eco-Warriors line, the Septic Tank sprayed toxic sludge for Cobra's eco-villains, its grime-covered toy finish revealing clean colors underneath after exposure to water.",
    "image": "images/septictank.jpg"
  },
  {
    "id": "cobra-piranha",
    "name": "Cobra Piranha",
    "fullName": "Cobra Piranha Attack Boat",
    "affiliation": "Cobra",
    "vehicleType": "Attack Boat",
    "firstYear": "1990",
    "crew": "1",
    "armament": "Torpedo launcher",
    "packagedWith": null,
    "bio": "A fast, low-profile Cobra attack boat, the Piranha used its torpedo launcher to strike G.I. Joe shipping and coastal positions before slipping away.",
    "image": "images/cobrapiranha.jpg"
  },
  {
    "id": "cobra-rage",
    "name": "Cobra Rage",
    "fullName": "Cobra Rage",
    "affiliation": "Cobra",
    "vehicleType": "Mine-Laying Tank",
    "firstYear": "1990",
    "crew": "1",
    "armament": "Land mine dispenser",
    "packagedWith": null,
    "bio": "A tracked Cobra vehicle built around a rear-mounted land mine dispenser, the Rage let Cobra seed minefields to slow advancing G.I. Joe forces.",
    "image": "images/cobrarage.jpg"
  },
  {
    "id": "general",
    "name": "The General",
    "fullName": "The General Missile Launcher",
    "affiliation": "G.I. Joe",
    "vehicleType": "Mobile Missile Launcher",
    "firstYear": "1990",
    "crew": "1",
    "armament": "Long-range missile launcher",
    "packagedWith": "Major Storm",
    "bio": "Commanded by Major Storm, the General was a massive tractor-trailer missile launcher that served as a mobile command and heavy-artillery platform for the G.I. Joe team.",
    "image": "images/thegeneral.jpg"
  },
  {
    "id": "hammer",
    "name": "Hammer",
    "fullName": "Hammer Assault Vehicle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Armored Humvee",
    "firstYear": "1990",
    "crew": "1",
    "armament": "Roof-mounted cannon",
    "packagedWith": null,
    "bio": "A heavily armored military Humvee, the Hammer gave the G.I. Joe team a fast, rugged assault vehicle for punching through Cobra roadblocks.",
    "image": "images/hammer.jpg"
  },
  {
    "id": "mobile-battle-bunker",
    "name": "Mobile Battle Bunker",
    "fullName": "Mobile Battle Bunker",
    "affiliation": "G.I. Joe",
    "vehicleType": "Mobile Command Vehicle",
    "firstYear": "1990",
    "crew": "2",
    "armament": "Twin cannons",
    "packagedWith": null,
    "bio": "A heavily armored tracked bunker on the move, the Mobile Battle Bunker gave the G.I. Joe team a rolling fortress for holding forward positions under fire.",
    "image": "images/mobilebattlebunker.jpg"
  },
  {
    "id": "destros-dominator",
    "name": "Destro's Dominator",
    "fullName": "Destro's Dominator",
    "affiliation": "Cobra",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1990",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "An armored Iron Grenadiers attack vehicle, Destro's Dominator gave the arms dealer's private army a fast, well-armed ride for field operations.",
    "image": "images/destrodominator.jpg"
  },
  {
    "id": "cobra-fang-ii",
    "name": "Cobra F.A.N.G. II",
    "fullName": "Fully Armed Negator Gyrocopter II",
    "affiliation": "Cobra",
    "vehicleType": "Mini-Helicopter",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Nose-mounted gun, twin missile launchers",
    "packagedWith": null,
    "bio": "A redesigned successor to the original Cobra F.A.N.G., the F.A.N.G. II was a compact one-man gyrocopter used for fast reconnaissance and hit-and-run strikes.",
    "image": "images/cobrafang2.jpg"
  },
  {
    "id": "crusader",
    "name": "Crusader",
    "fullName": "Crusader Space Shuttle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Space Shuttle",
    "firstYear": "1989",
    "crew": "1",
    "armament": "None (transport craft)",
    "packagedWith": "Payload",
    "bio": "The G.I. Joe team's own space shuttle, the Crusader carried astronaut Payload into orbit to counter Cobra's growing presence in space.",
    "image": "images/crusader.jpg"
  },
  {
    "id": "cobra-devastator",
    "name": "Cobra Devastator",
    "fullName": "Cobra Battlefield Robot: Devastator",
    "affiliation": "Cobra",
    "vehicleType": "Battlefield Robot",
    "firstYear": "1989",
    "crew": "0 (remote/robotic)",
    "armament": "Rotating cannon turret",
    "packagedWith": null,
    "bio": "A treaded, remote-operated battlefield robot, the Devastator rolled into combat under its own power to soften up enemy positions before Cobra troops advanced.",
    "image": "images/cobradevastator.jpg"
  },
  {
    "id": "cobra-hovercraft",
    "name": "Cobra Hovercraft",
    "fullName": "Cobra Battlefield Robot: Hovercraft",
    "affiliation": "Cobra",
    "vehicleType": "Battlefield Robot",
    "firstYear": "1989",
    "crew": "0 (remote/robotic)",
    "armament": "Mounted blaster",
    "packagedWith": null,
    "bio": "One of the Cobra Battlefield Robots, the Hovercraft skimmed over land and water alike, giving Cobra an unmanned scout and skirmisher for terrain G.I. Joe vehicles could not easily cross.",
    "image": "images/cobrahovercraft.jpg"
  },
  {
    "id": "cobra-radar-rat",
    "name": "Cobra Radar Rat",
    "fullName": "Cobra Battlefield Robot: Radar Rat",
    "affiliation": "Cobra",
    "vehicleType": "Battlefield Robot",
    "firstYear": "1989",
    "crew": "0 (remote/robotic)",
    "armament": "Spring-loaded missile",
    "packagedWith": null,
    "bio": "A small rodent-shaped battlefield robot topped with a rotating radar dish, the Radar Rat scouted ahead of Cobra patrols and relayed enemy positions.",
    "image": "images/cobraradarrat.jpg"
  },
  {
    "id": "tri-blaster",
    "name": "Tri-Blaster",
    "fullName": "G.I. Joe Battlefield Robot: Tri-Blaster",
    "affiliation": "G.I. Joe",
    "vehicleType": "Battlefield Robot",
    "firstYear": "1989",
    "crew": "0 (remote/robotic)",
    "armament": "Triple cannon turret",
    "packagedWith": null,
    "bio": "The heaviest of the G.I. Joe Battlefield Robots, the Tri-Blaster mounted a triple cannon turret on a small mobile chassis to provide unmanned covering fire.",
    "image": "images/triblaster.jpg"
  },
  {
    "id": "raider",
    "name": "Raider",
    "fullName": "Raider Front Line Defense Vehicle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Light Attack Tank",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Elevating cannon",
    "packagedWith": "Hot Seat",
    "bio": "Driven by Hot Seat, the Raider was a fast, low-profile tracked vehicle built to punch through Cobra's front lines and clear the way for heavier G.I. Joe armor.",
    "image": "images/raider.jpg"
  },
  {
    "id": "thunderclap",
    "name": "Thunderclap",
    "fullName": "Thunderclap Mobile Missile Complex",
    "affiliation": "G.I. Joe",
    "vehicleType": "Mobile Artillery",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Long-range missile launcher",
    "packagedWith": "Long Range",
    "bio": "Manned by the artillery specialist Long Range, the Thunderclap was a three-piece mobile missile launcher that let the G.I. Joe team deliver long-range fire support.",
    "image": "images/thunderclap.jpg"
  },
  {
    "id": "pulverizer",
    "name": "Pulverizer",
    "fullName": "Battle Force 2000 Pulverizer",
    "affiliation": "G.I. Joe",
    "vehicleType": "Assault Tank",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Forward-mounted rocket launcher",
    "packagedWith": null,
    "bio": "Part of the Battle Force 2000 line, the Pulverizer was a compact assault tank designed to soften up hardened Cobra positions ahead of the rest of the team.",
    "image": "images/pulverizer.jpg"
  },
  {
    "id": "darklons-evader",
    "name": "Darklon's Evader",
    "fullName": "Darklon's Evader",
    "affiliation": "Cobra",
    "vehicleType": "Assault Vehicle",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Twin cannons",
    "packagedWith": "Darklon",
    "bio": "Piloted by the mercenary Darklon, the Evader was a rugged, heavily armed assault vehicle used by the Iron Grenadiers to run supplies and firepower through hostile terrain.",
    "image": "images/darklonsevader.jpg"
  },
  {
    "id": "destros-razorback",
    "name": "Destro's Razorback",
    "fullName": "Destro's Razorback",
    "affiliation": "Cobra",
    "vehicleType": "Amphibious Assault Vehicle",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Rear-mounted cannon",
    "packagedWith": "Wild Boar",
    "bio": "Driven by Wild Boar, the Razorback was an amphibious Iron Grenadiers vehicle capable of crossing water and rough terrain alike to keep Destro's forces supplied and mobile.",
    "image": "images/destrorazorback.jpg"
  },
  {
    "id": "night-boomer",
    "name": "Night Boomer",
    "fullName": "Night Force Night Boomer",
    "affiliation": "G.I. Joe",
    "vehicleType": "Assault Boat",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "A Toys \"R\" Us-exclusive Night Force release, the matte-black Night Boomer let the G.I. Joe team run covert waterborne operations under cover of darkness.",
    "image": "images/nightboomer.jpg"
  },
  {
    "id": "night-ray",
    "name": "Night Ray",
    "fullName": "Night Force Night Ray",
    "affiliation": "G.I. Joe",
    "vehicleType": "Hydrofoil",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Depth charges, mounted gun",
    "packagedWith": null,
    "bio": "Part of the Toys \"R\" Us-exclusive Night Force line, the Night Ray was a stealth-black hydrofoil used by the G.I. Joe team for nighttime coastal strikes.",
    "image": "images/nightray.jpg"
  },
  {
    "id": "night-scrambler",
    "name": "Night Scrambler",
    "fullName": "Night Force Night Scrambler",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Buggy",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Mounted machine gun",
    "packagedWith": null,
    "bio": "A Toys \"R\" Us-exclusive Night Force vehicle, the Night Scrambler was a matte-black attack buggy built for fast, covert night raids.",
    "image": "images/nightscrambler.jpg"
  },
  {
    "id": "armadillo-marauders",
    "name": "Armadillo (Slaughter's Marauders)",
    "fullName": "Slaughter's Marauders Armadillo",
    "affiliation": "G.I. Joe",
    "vehicleType": "Mini-Tank",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Turret-mounted cannon",
    "packagedWith": null,
    "bio": "Part of Sgt. Slaughter's Marauders line, the Armadillo was a compact, heavily armored mini-tank built to roll straight through Cobra defenses.",
    "image": "images/armadillo2.jpg"
  },
  {
    "id": "equalizer",
    "name": "Equalizer",
    "fullName": "Slaughter's Marauders Equalizer",
    "affiliation": "G.I. Joe",
    "vehicleType": "Mobile Artillery",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Elevating rocket launcher",
    "packagedWith": null,
    "bio": "Another vehicle from Sgt. Slaughter's Marauders line, the Equalizer was a tracked mobile artillery piece that gave the team long-range fire support in the field.",
    "image": "images/equalizer.jpg"
  },
  {
    "id": "lynx",
    "name": "Lynx",
    "fullName": "Slaughter's Marauders Lynx",
    "affiliation": "G.I. Joe",
    "vehicleType": "Snow Vehicle",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Mounted gun",
    "packagedWith": null,
    "bio": "A snow-going vehicle from Sgt. Slaughter's Marauders line, the Lynx let the team operate in arctic terrain that would bog down conventional wheeled vehicles.",
    "image": "images/lynx.jpg"
  },
  {
    "id": "tiger-fish",
    "name": "Tiger Fish",
    "fullName": "Tiger Force Tiger Fish",
    "affiliation": "G.I. Joe",
    "vehicleType": "Swamp Attack Boat",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Mounted gun",
    "packagedWith": null,
    "bio": "A jungle-camouflaged Tiger Force release, the Tiger Fish was a swamp attack boat that let the G.I. Joe team chase Cobra forces through marshland and shallow water.",
    "image": "images/tigerfish.jpg"
  },
  {
    "id": "tiger-sting",
    "name": "Tiger Sting",
    "fullName": "Tiger Force Tiger Sting",
    "affiliation": "G.I. Joe",
    "vehicleType": "Night Attack 4-WD",
    "firstYear": "1989",
    "crew": "1",
    "armament": "Mounted gun",
    "packagedWith": null,
    "bio": "Finished in Tiger Force jungle camouflage, the Tiger Sting was a fast 4-WD attack vehicle used by the team for rapid jungle assaults.",
    "image": "images/tigersting.jpg"
  },
  {
    "id": "cobra-adder",
    "name": "Cobra Adder",
    "fullName": "Cobra Adder",
    "affiliation": "Cobra",
    "vehicleType": "Armored Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A boxy, heavily armored Cobra assault vehicle, the Adder gave Cobra troops a mobile shield to advance behind.",
    "image": "images/cobraadder.jpg"
  },
  {
    "id": "cobra-battle-barge",
    "name": "Cobra Battle Barge",
    "fullName": "Cobra Battle Barge",
    "affiliation": "Cobra",
    "vehicleType": "Watercraft",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A Cobra watercraft built for river and coastal assaults, the Battle Barge let Cobra bring firepower onto the water.",
    "image": "images/cobrabattlebarge.jpg"
  },
  {
    "id": "cobra-bugg",
    "name": "Cobra B.U.G.G.",
    "fullName": "Cobra BUGG",
    "affiliation": "Cobra",
    "vehicleType": "All-Terrain Buggy",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Secto-Viper",
    "bio": "An all-terrain buggy driven by Secto-Viper, the Cobra BUGG gave Cobra a fast, nimble ride for scouting and raids.",
    "image": "images/cobrabugg.jpg"
  },
  {
    "id": "cobra-imp",
    "name": "Cobra Imp",
    "fullName": "Cobra Imp",
    "affiliation": "Cobra",
    "vehicleType": "Mini Escape Craft",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Three ambush missiles",
    "packagedWith": null,
    "bio": "A tiny escape craft armed with three ambush missiles, the Cobra Imp let a single Cobra trooper make a fast, armed getaway.",
    "image": "images/cobraimp.jpg"
  },
  {
    "id": "cobra-stellar-stiletto",
    "name": "Cobra Stellar Stiletto",
    "fullName": "Cobra Stellar Stiletto",
    "affiliation": "Cobra",
    "vehicleType": "Fighter Jet",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Star-Viper",
    "bio": "A sleek fighter jet flown by Star-Viper, the Stellar Stiletto gave Cobra fast air support.",
    "image": "images/cobrastellarstilleto.jpg"
  },
  {
    "id": "desert-fox-6wd",
    "name": "Desert Fox 6WD",
    "fullName": "Desert Fox 6 W.D.",
    "affiliation": "G.I. Joe",
    "vehicleType": "6-Wheel-Drive Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Skidmark",
    "bio": "A rugged six-wheel-drive vehicle driven by Skidmark, the Desert Fox let the G.I. Joe team cross harsh desert terrain other vehicles couldn't handle.",
    "image": "images/desertfox.jpg"
  },
  {
    "id": "mean-dog",
    "name": "Mean Dog",
    "fullName": "Mean Dog",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Wild Card",
    "bio": "An armored attack vehicle driven by Wild Card, the Mean Dog gave the G.I. Joe team a tough, aggressive ride into combat.",
    "image": "images/meandog.jpg"
  },
  {
    "id": "phantom-x19",
    "name": "Phantom X-19",
    "fullName": "Stealth Fighter",
    "affiliation": "G.I. Joe",
    "vehicleType": "Stealth Jet",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Ghostrider",
    "bio": "A stealth fighter jet flown by Ghostrider, the Phantom X-19 let the G.I. Joe team strike from the air while evading enemy radar.",
    "image": "images/phantomx19.jpg"
  },
  {
    "id": "rpv",
    "name": "R.P.V.",
    "fullName": "Remote Piloted Vehicle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Remote-Controlled Vehicle",
    "firstYear": "1988",
    "crew": "0 (remote piloted)",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "An unmanned remote-piloted vehicle, the R.P.V. let the G.I. Joe team scout and strike without risking a driver.",
    "image": "images/rpv.jpg"
  },
  {
    "id": "skystorm",
    "name": "Skystorm",
    "fullName": "X-Wing Chopper",
    "affiliation": "G.I. Joe",
    "vehicleType": "Helicopter",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Windmill",
    "bio": "An X-wing chopper flown by Windmill, the Skystorm gave the G.I. Joe team a distinctive helicopter with crossed rotor blades.",
    "image": "images/skystorm.jpg"
  },
  {
    "id": "swampmasher",
    "name": "Swampmasher",
    "fullName": "Swampmasher",
    "affiliation": "G.I. Joe",
    "vehicleType": "Swamp Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A rugged swamp vehicle, the Swampmasher let the G.I. Joe team cross marsh and wetland terrain that would bog down ordinary trucks.",
    "image": "images/swampmasher.jpg"
  },
  {
    "id": "warthog-aifv",
    "name": "Warthog A.I.F.V.",
    "fullName": "Amphibious Infantry Fighting Vehicle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Amphibious Fighting Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Sgt. Slaughter",
    "bio": "An amphibious infantry fighting vehicle driven by Sgt. Slaughter, the Warthog let the G.I. Joe team fight equally well on land and water.",
    "image": "images/warthog.jpg"
  },
  {
    "id": "agp",
    "name": "A.G.P.",
    "fullName": "Anti-Gravity Pod",
    "affiliation": "Cobra",
    "vehicleType": "Hovering Pod",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Nullifier",
    "bio": "A hovering anti-gravity pod piloted by Nullifier of the Iron Grenadiers, the A.G.P. let a single trooper float above rough terrain.",
    "image": "images/agp.jpg"
  },
  {
    "id": "demon",
    "name": "D.E.M.O.N.",
    "fullName": "Dual Elevating Multi-Ordnance Neutralizer",
    "affiliation": "Cobra",
    "vehicleType": "Armored Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Dual elevating cannons",
    "packagedWith": "Ferret",
    "bio": "An Iron Grenadiers vehicle driven by Ferret, the D.E.M.O.N. mounts dual elevating cannons capable of neutralizing multiple types of ordnance.",
    "image": "images/demon.jpg"
  },
  {
    "id": "destros-despoiler",
    "name": "Destro's Despoiler",
    "fullName": "Destro's Despoiler",
    "affiliation": "Cobra",
    "vehicleType": "Personal Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Destro",
    "bio": "Destro's personal attack vehicle for the Iron Grenadiers, the Despoiler let the arms dealer lead his own troops into battle.",
    "image": "images/destrodespoiler.jpg"
  },
  {
    "id": "tiger-paw",
    "name": "Tiger Paw",
    "fullName": "Tiger Paw",
    "affiliation": "G.I. Joe",
    "vehicleType": "All-Terrain Vehicle",
    "firstYear": "1988",
    "crew": "2",
    "armament": "Removable mounted weapon",
    "packagedWith": null,
    "bio": "A jungle-camouflaged Tiger Force retool of the Ferret ATV, the Tiger Paw let the elite jungle-fighting unit cover rough terrain quickly.",
    "image": "images/tigerpaw.jpg"
  },
  {
    "id": "tiger-fly",
    "name": "Tiger Fly",
    "fullName": "Tiger Fly",
    "affiliation": "G.I. Joe",
    "vehicleType": "Aircraft",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Recondo",
    "bio": "A jungle-camouflaged Tiger Force aircraft flown by Recondo, the Tiger Fly gave the elite jungle unit air support.",
    "image": "images/tigerfly.jpg"
  },
  {
    "id": "tiger-cat",
    "name": "Tiger Cat",
    "fullName": "Tiger Cat",
    "affiliation": "G.I. Joe",
    "vehicleType": "Tank",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": "Frostbite",
    "bio": "A jungle-camouflaged Tiger Force tank driven by Frostbite, the Tiger Cat gave the elite jungle unit armored firepower.",
    "image": "images/tigercat.jpg"
  },
  {
    "id": "tiger-rat",
    "name": "Tiger Rat",
    "fullName": "Tiger Rat",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A jungle-camouflaged Tiger Force attack vehicle, the Tiger Rat gave the elite jungle unit a fast ride into combat.",
    "image": "images/tigerrat.jpg"
  },
  {
    "id": "tiger-shark",
    "name": "Tiger Shark",
    "fullName": "Tiger Shark",
    "affiliation": "G.I. Joe",
    "vehicleType": "Watercraft",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A jungle-camouflaged Tiger Force watercraft, the Tiger Shark let the elite jungle unit strike along rivers and coastlines.",
    "image": "images/tigershark.jpg"
  },
  {
    "id": "night-blaster",
    "name": "Night Blaster",
    "fullName": "Night Blaster",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A Toys R Us-exclusive Night Force vehicle finished in black with glow-in-the-dark battle labels, the Night Blaster was built for covert nighttime operations.",
    "image": "images/nightblaster.jpg"
  },
  {
    "id": "night-raider",
    "name": "Night Raider",
    "fullName": "Night Raider",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A Toys R Us-exclusive Night Force vehicle finished in black with glow-in-the-dark battle labels, the Night Raider was built for covert nighttime operations.",
    "image": "images/nightraider.jpg"
  },
  {
    "id": "night-shade",
    "name": "Night Shade",
    "fullName": "Night Shade",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A Toys R Us-exclusive Night Force vehicle finished in black with glow-in-the-dark battle labels, the Night Shade was built for covert nighttime operations.",
    "image": "images/nightshade.jpg"
  },
  {
    "id": "night-storm",
    "name": "Night Storm",
    "fullName": "Night Storm",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A Toys R Us-exclusive Night Force vehicle finished in black with glow-in-the-dark battle labels, the Night Storm was built for covert nighttime operations.",
    "image": "images/nightstorm.jpg"
  },
  {
    "id": "night-striker",
    "name": "Night Striker",
    "fullName": "Night Striker",
    "affiliation": "G.I. Joe",
    "vehicleType": "Attack Vehicle",
    "firstYear": "1988",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A Toys R Us-exclusive Night Force vehicle finished in black with glow-in-the-dark battle labels, the Night Striker was built for covert nighttime operations.",
    "image": "images/nightstriker.jpg"
  },
  {
    "id": "buzz-boar",
    "name": "Cobra Buzz Boar",
    "fullName": "Buzz Boar",
    "affiliation": "Cobra",
    "vehicleType": "Mini Tracked Vehicle",
    "firstYear": "1987",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A small tracked assault vehicle, the Cobra Buzz Boar let a single Cobra trooper bring mobile firepower into tight spaces.",
    "image": "images/cobrabuzzbear.jpg"
  },
  {
    "id": "cobra-pogo",
    "name": "Cobra Pogo Ballistic Battle Ball",
    "fullName": "Cobra Pogo Ballistic Battle Ball",
    "affiliation": "Cobra",
    "vehicleType": "Bouncing Combat Pod",
    "firstYear": "1987",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "An unusual spring-loaded combat pod that bounced across the battlefield, the Cobra Pogo Ballistic Battle Ball gave a single Cobra trooper an unpredictable way to close on a target.",
    "image": "images/cobrapogo.jpg"
  },
  {
    "id": "road-toad",
    "name": "Road Toad",
    "fullName": "Road Toad B.R.V. (Battlefield Recovery Vehicle)",
    "affiliation": "G.I. Joe",
    "vehicleType": "Recovery Vehicle",
    "firstYear": "1987",
    "crew": "1",
    "armament": "None listed",
    "packagedWith": null,
    "bio": "A battlefield recovery vehicle, the Road Toad let the G.I. Joe team tow and salvage damaged equipment from the front lines.",
    "image": "images/roadtoad.jpg"
  },
  {
    "id": "slam",
    "name": "S.L.A.M.",
    "fullName": "Strategic Long-Range Artillery Machine",
    "affiliation": "G.I. Joe",
    "vehicleType": "Artillery Vehicle",
    "firstYear": "1987",
    "crew": "1",
    "armament": "Long-range artillery cannon",
    "packagedWith": null,
    "bio": "A strategic long-range artillery machine, the S.L.A.M. gave the G.I. Joe team a mobile platform for striking targets from well outside the front line.",
    "image": "images/slam.jpg"
  },
  {
    "id": "mobile-command-center",
    "name": "Mobile Command Center",
    "fullName": "Mobile Command Center",
    "affiliation": "G.I. Joe",
    "vehicleType": "Command Truck",
    "firstYear": "1987",
    "crew": "1",
    "armament": "None listed",
    "packagedWith": "Steam-Roller",
    "bio": "A rolling command post driven by Steam-Roller, the Mobile Command Center let the G.I. Joe team coordinate operations from wherever the battle took them.",
    "image": "images/mobilecommandcenter.jpg"
  },
  {
    "id": "dominator",
    "name": "Dominator",
    "fullName": "Snow Tank",
    "affiliation": "G.I. Joe",
    "vehicleType": "Snow Tank",
    "firstYear": "1987",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "One of the six Battle Force 2000 vehicles that could combine into the Future Fortress, the Dominator was a snow tank built for arctic combat.",
    "image": "images/dominator.jpg"
  },
  {
    "id": "eliminator-4wd",
    "name": "Eliminator",
    "fullName": "4WD",
    "affiliation": "G.I. Joe",
    "vehicleType": "4-Wheel-Drive Jeep",
    "firstYear": "1987",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "One of the six Battle Force 2000 vehicles that could combine into the Future Fortress, the Eliminator was a fast 4-wheel-drive jeep.",
    "image": "images/eliminator.jpg"
  },
  {
    "id": "marauder-cycle-tank",
    "name": "Marauder",
    "fullName": "Motorcycle-Tank",
    "affiliation": "G.I. Joe",
    "vehicleType": "Motorcycle-Tank",
    "firstYear": "1987",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "One of the six Battle Force 2000 vehicles that could combine into the Future Fortress, the Marauder was a hybrid motorcycle-tank.",
    "image": "images/marauder.jpg"
  },
  {
    "id": "sky-sweeper",
    "name": "Sky Sweeper",
    "fullName": "Anti-Aircraft Tank",
    "affiliation": "G.I. Joe",
    "vehicleType": "Anti-Aircraft Tank",
    "firstYear": "1987",
    "crew": "1",
    "armament": "Anti-aircraft cannon",
    "packagedWith": null,
    "bio": "One of the six Battle Force 2000 vehicles that could combine into the Future Fortress, the Sky Sweeper was a tank built to knock enemy aircraft from the sky.",
    "image": "images/skysweeper.jpg"
  },
  {
    "id": "dreadnok-air-skiff",
    "name": "Dreadnok Air Skiff",
    "fullName": "Air Skiff",
    "affiliation": "Cobra",
    "vehicleType": "Flying Skiff",
    "firstYear": "1987",
    "crew": "1",
    "armament": "None listed",
    "packagedWith": "Zanzibar",
    "bio": "A flying skiff piloted by the Dreadnok pirate Zanzibar, the Air Skiff let the biker gang raid targets from the air.",
    "image": "images/dreadnokairskiff.jpg"
  },
  {
    "id": "cobra-night-raven",
    "name": "Cobra Night Raven S³P",
    "fullName": "Cobra Night Raven S³P",
    "affiliation": "Cobra",
    "vehicleType": "Stealth Jet",
    "firstYear": "1986",
    "crew": "1",
    "armament": "Missiles, mounted cannon",
    "packagedWith": "Strato-Viper",
    "bio": "A sleek stealth jet flown by Strato-Viper, the Night Raven S³P lets Cobra strike from the air while evading radar detection.",
    "image": "images/cobranightraven.jpg"
  },
  {
    "id": "havoc",
    "name": "H.A.V.O.C.",
    "fullName": "Heavy Articulated Vehicle Ordnance Carrier",
    "affiliation": "G.I. Joe",
    "vehicleType": "Armored Personnel Carrier",
    "firstYear": "1986",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": "Cross-Country",
    "bio": "A large, heavily armored ordnance carrier driven by Cross-Country, the H.A.V.O.C. gives the G.I. Joe team an armored platform for carrying troops and firepower together.",
    "image": "images/havoc.jpg"
  },
  {
    "id": "devilfish",
    "name": "Devilfish",
    "fullName": "Devilfish",
    "affiliation": "Cobra",
    "vehicleType": "Swamp Attack Boat",
    "firstYear": "1986",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "A Cobra attack boat built to skim across swamps and shallow water, the Devilfish let Cobra strike in terrain most vehicles could not cross.",
    "image": "images/devilfish.jpg"
  },
  {
    "id": "triple-t",
    "name": "Triple 'T'",
    "fullName": "Tag Team Terminator",
    "affiliation": "G.I. Joe",
    "vehicleType": "Heavy Tank",
    "firstYear": "1986",
    "crew": "1",
    "armament": "Dual cannons",
    "packagedWith": "Sgt. Slaughter",
    "bio": "A massive dual-cannon tank driven by Sgt. Slaughter, the Triple 'T' was one of the largest ground vehicles the G.I. Joe team fielded.",
    "image": "images/triplet.jpg"
  },
  {
    "id": "air-chariot",
    "name": "Air Chariot",
    "fullName": "Air Chariot",
    "affiliation": "Cobra",
    "vehicleType": "Flying Throne",
    "firstYear": "1986",
    "crew": "1",
    "armament": "None listed",
    "packagedWith": "Serpentor",
    "bio": "A flying throne built for Cobra Emperor Serpentor, the Air Chariot let Cobra's ruler survey and command the battlefield from above.",
    "image": "images/airchariot.jpg"
  },
  {
    "id": "cobra-stun",
    "name": "Cobra Stun",
    "fullName": "Cobra Stun",
    "affiliation": "Cobra",
    "vehicleType": "Attack Cycle",
    "firstYear": "1986",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Motor-Viper",
    "bio": "A single-track attack cycle ridden by Motor-Viper, the Cobra Stun gave Cobra a fast, nimble ride for hit-and-run strikes.",
    "image": "images/cobrastun.jpg"
  },
  {
    "id": "dreadnok-swampfire",
    "name": "Dreadnok Swampfire",
    "fullName": "Dreadnok Swampfire",
    "affiliation": "Dreadnoks",
    "vehicleType": "Swamp Boat",
    "firstYear": "1986",
    "crew": "1",
    "armament": "None listed",
    "packagedWith": null,
    "bio": "A rugged swamp boat used by the Dreadnoks, the Swampfire let the biker gang chase targets through marshland other vehicles couldn't reach.",
    "image": "images/dreadnokswampfire.jpg"
  },
  {
    "id": "armadillo-mini-tank",
    "name": "Armadillo",
    "fullName": "Mini Tank Armadillo",
    "affiliation": "G.I. Joe",
    "vehicleType": "Mini Tank",
    "firstYear": "1985",
    "crew": "3",
    "armament": "Swiveling, elevating twin cannons",
    "packagedWith": null,
    "bio": "A compact tracked mini tank that carries up to three figures, the Armadillo brings swiveling, elevating cannons to close-quarters ground combat.",
    "image": "images/armadillo1.jpg"
  },
  {
    "id": "cobra-ferret-atv",
    "name": "Cobra Ferret ATV",
    "fullName": "Ferret ATV",
    "affiliation": "Cobra",
    "vehicleType": "All-Terrain Vehicle",
    "firstYear": "1985",
    "crew": "2",
    "armament": "Removable mounted weapon",
    "packagedWith": null,
    "bio": "A four-wheel-drive all-terrain vehicle carrying two riders, the Cobra Ferret ATV let troops cover rough ground quickly while still bringing a mounted weapon along.",
    "image": "images/cobraferretatv.jpg"
  },
  {
    "id": "cobra-moray",
    "name": "Cobra Moray",
    "fullName": "Hydrofoil",
    "affiliation": "Cobra",
    "vehicleType": "Hydrofoil",
    "firstYear": "1985",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": "Lampreys",
    "bio": "A fast hydrofoil piloted by Lampreys, the Cobra Moray let Cobra strike quickly across open water.",
    "image": "images/cobramoray.jpg"
  },
  {
    "id": "silver-mirage",
    "name": "Silver Mirage",
    "fullName": "Silver Mirage Motorcycle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Motorcycle",
    "firstYear": "1985",
    "crew": "3",
    "armament": "None listed",
    "packagedWith": null,
    "bio": "A motorcycle and sidecar combination capable of carrying up to three figures, the Silver Mirage gave the G.I. Joe team a fast way to move a small squad together.",
    "image": "images/silvermirage.jpg"
  },
  {
    "id": "cobra-cat",
    "name": "Cobra C.A.T.",
    "fullName": "Motorized Crimson Attack Tank",
    "affiliation": "Cobra",
    "vehicleType": "Tank",
    "firstYear": "1985",
    "crew": "1",
    "armament": "Tank cannon",
    "packagedWith": null,
    "bio": "A Sears-exclusive tank built from a retooled M.O.B.A.T. mold, the Crimson Attack Tank gave the Crimson Guard a tank of their own that could climb tough terrain and turn like the real thing.",
    "image": "images/cobracat.jpg"
  },
  {
    "id": "cobra-asp",
    "name": "Cobra A.S.P.",
    "fullName": "Assault System Pod",
    "affiliation": "Cobra",
    "vehicleType": "Assault Vehicle",
    "firstYear": "1984",
    "crew": "1",
    "armament": "Front-mounted cannon",
    "packagedWith": null,
    "bio": "A compact, heavily armored one-man assault vehicle, the Cobra A.S.P. gave Cobra a fast strike platform for hit-and-run attacks.",
    "image": "images/cobrasp.jpg"
  },
  {
    "id": "cobra-claw",
    "name": "Cobra C.L.A.W.",
    "fullName": "Covert Light Aerial Weapon",
    "affiliation": "Cobra",
    "vehicleType": "Mini Helicopter",
    "firstYear": "1984",
    "crew": "1",
    "armament": "Mounted cannon",
    "packagedWith": null,
    "bio": "A small, covert one-man helicopter, the Cobra C.L.A.W. let a single pilot slip into a battle zone undetected before striking with its mounted cannon.",
    "image": "images/cobraclaw.jpg"
  },
  {
    "id": "slugger",
    "name": "Slugger",
    "fullName": "Self-Propelled Cannon",
    "affiliation": "G.I. Joe",
    "vehicleType": "Self-Propelled Artillery",
    "firstYear": "1984",
    "crew": "1",
    "armament": "Large-bore cannon",
    "packagedWith": "Thunder",
    "bio": "A self-propelled cannon carrying a single gunner, the Slugger gave the G.I. Joe team mobile heavy artillery that could keep pace with fast-moving operations.",
    "image": "images/slugger.jpg"
  },
  {
    "id": "stinger",
    "name": "Stinger",
    "fullName": "Cobra Night Attack 4-WD",
    "affiliation": "Cobra",
    "vehicleType": "4-Wheel-Drive Attack Vehicle",
    "firstYear": "1984",
    "crew": "1",
    "armament": "Mounted machine gun",
    "packagedWith": "Stinger Driver",
    "bio": "A rugged 4-wheel-drive attack buggy built for night raids, the Stinger gave Cobra a fast, armed vehicle for hit-and-run assaults.",
    "image": "images/stinger.jpg"
  },
  {
    "id": "sky-hawk-vtol",
    "name": "Sky Hawk",
    "fullName": "Vertical Take-Off & Landing Aircraft",
    "affiliation": "G.I. Joe",
    "vehicleType": "One-Man V.T.O.L.",
    "firstYear": "1984",
    "crew": "1",
    "armament": "Removable rockets",
    "packagedWith": null,
    "bio": "A one-man V.T.O.L. aircraft with rotating engines and removable rockets, the Sky Hawk let a single G.I. Joe pilot take off and land vertically anywhere on the battlefield.",
    "image": "images/skyhawk.jpg"
  },
  {
    "id": "manta",
    "name": "M.A.N.T.A.",
    "fullName": "Marine Assault Nautical Transport: Air Driven",
    "affiliation": "G.I. Joe",
    "vehicleType": "Air Boat",
    "firstYear": "1984",
    "crew": "1",
    "armament": "Mounted weaponry",
    "packagedWith": null,
    "bio": "An air-driven assault boat available exclusively through mail order, the M.A.N.T.A. let the G.I. Joe team move quickly and quietly through swamps and shallow water.",
    "image": "images/manta.jpg"
  },
  {
    "id": "fang",
    "name": "Cobra F.A.N.G.",
    "fullName": "A Fully Armed Negator Gyrocopter",
    "affiliation": "Cobra",
    "vehicleType": "Mini Helicopter",
    "firstYear": "1983",
    "crew": "1",
    "armament": "Nose-mounted cannon, movable rotor blades",
    "packagedWith": null,
    "bio": "A tiny one-man gyrocopter, the Cobra F.A.N.G. gave Cobra a cheap, fast way to put an armed pilot in the air, and its compact size made it a mainstay of Cobra bases for years.",
    "image": "images/cobrafang.jpg"
  },
  {
    "id": "apc",
    "name": "A.P.C.",
    "fullName": "Amphibious Personnel Carrier",
    "affiliation": "G.I. Joe",
    "vehicleType": "Amphibious Troop Carrier",
    "firstYear": "1983",
    "crew": "Holds 23 figures",
    "armament": "None (troop transport)",
    "packagedWith": null,
    "bio": "A boxy amphibious troop carrier capable of holding two dozen G.I. Joe figures at once, the A.P.C. let the team ferry large numbers of troops across both land and water.",
    "image": "images/apc.jpg"
  },
  {
    "id": "polar-battle-bear",
    "name": "Polar Battle Bear",
    "fullName": "Skimobile",
    "affiliation": "G.I. Joe",
    "vehicleType": "Snowmobile",
    "firstYear": "1983",
    "crew": "1",
    "armament": "Twin laser blasters",
    "packagedWith": null,
    "bio": "A one-man snowmobile armed with twin laser blasters, the Polar Battle Bear gave the G.I. Joe team a fast way to cross snow and ice while still bringing firepower to bear.",
    "image": "images/polarbattlebear.jpg"
  },
  {
    "id": "snake-armor",
    "name": "S.N.A.K.E.",
    "fullName": "Battle Armor",
    "affiliation": "G.I. Joe",
    "vehicleType": "Powered Battle Armor",
    "firstYear": "1983",
    "crew": "1",
    "armament": "Four removable weapon pods",
    "packagedWith": null,
    "bio": "A wearable suit of powered battle armor with four removable weapon pods, the S.N.A.K.E. let a single soldier become a walking arsenal.",
    "image": "images/snake.jpg"
  },
  {
    "id": "whirlwind",
    "name": "Whirlwind",
    "fullName": "Twin Battle Gun Whirlwind",
    "affiliation": "G.I. Joe",
    "vehicleType": "Tracked Gun Platform",
    "firstYear": "1983",
    "crew": "1",
    "armament": "Twin-mounted rotating guns",
    "packagedWith": null,
    "bio": "A tracked platform mounting twin rotating guns, the Whirlwind gave a single gunner mobile, all-around firepower on the battlefield.",
    "image": "images/whirlwind.jpg"
  },
  {
    "id": "falcon-glider",
    "name": "Falcon",
    "fullName": "G.I. Joe Attack Glider",
    "affiliation": "G.I. Joe",
    "vehicleType": "Glider",
    "firstYear": "1983",
    "crew": "1",
    "armament": "None (unpowered glider)",
    "packagedWith": "Grunt",
    "bio": "An unpowered attack glider that let a single G.I. Joe pilot soar, loop, and glide silently over the battlefield.",
    "image": "images/falconglider.jpg"
  },
  {
    "id": "cobra-viper-glider",
    "name": "Viper",
    "fullName": "Cobra Command Attack Glider",
    "affiliation": "Cobra",
    "vehicleType": "Glider",
    "firstYear": "1983",
    "crew": "1",
    "armament": "None (unpowered glider)",
    "packagedWith": "Cobra Viper Pilot",
    "bio": "Cobra's answer to the G.I. Joe Falcon, this unpowered attack glider let a single Viper pilot soar and glide over the battlefield.",
    "image": "images/viperglider.jpg"
  },
  {
    "id": "hal",
    "name": "H.A.L.",
    "fullName": "Heavy Artillery Laser",
    "affiliation": "G.I. Joe",
    "vehicleType": "Towed Artillery",
    "firstYear": "1982",
    "crew": "1",
    "armament": "Swiveling, elevating laser cannon",
    "packagedWith": "Grand Slam",
    "bio": "A towed heavy laser cannon operated by a single gunner, the H.A.L. gave the earliest G.I. Joe team a mobile, elevating artillery piece that could be wheeled into position and swiveled onto target.",
    "image": "images/hal.jpg"
  },
  {
    "id": "mms",
    "name": "M.M.S.",
    "fullName": "Mobile Missile System",
    "affiliation": "G.I. Joe",
    "vehicleType": "Towed Missile Launcher",
    "firstYear": "1982",
    "crew": "1",
    "armament": "Elevating, swiveling missile launcher with removable missiles",
    "packagedWith": "Hawk",
    "bio": "A towed missile battery operated by a single gunner, the M.M.S. let the G.I. Joe team bring elevating, swiveling long-range firepower to bear wherever a mission required it.",
    "image": "images/mms.jpg"
  },
  {
    "id": "ram-cycle",
    "name": "R.A.M.",
    "fullName": "Rapid Fire Motorcycle",
    "affiliation": "G.I. Joe",
    "vehicleType": "Motorcycle",
    "firstYear": "1982",
    "crew": "1",
    "armament": "Vulcan 20mm Gatling cannon",
    "packagedWith": null,
    "bio": "A fast attack motorcycle armed with a Vulcan 20mm Gatling cannon, the R.A.M. let a single rider bring rapid, mobile firepower to the battlefield.",
    "image": "images/ram.jpg"
  },
  {
    "id": "flak-cannon",
    "name": "F.L.A.K.",
    "fullName": "Field Light Attack Cannon",
    "affiliation": "G.I. Joe",
    "vehicleType": "Towed Anti-Aircraft Cannon",
    "firstYear": "1982",
    "crew": "1",
    "armament": "Swiveling, elevating attack cannon",
    "packagedWith": null,
    "bio": "A towed anti-aircraft cannon operated by a single gunner, the F.L.A.K. gave the G.I. Joe team mobile, elevating firepower against low-flying threats.",
    "image": "images/flak.jpg"
  },
  {
    id: 'vamp',
    name: 'V.A.M.P.',
    fullName: 'Vehicle: Attack: Multi-Purpose',
    affiliation: 'G.I. Joe',
    vehicleType: 'Jeep',
    firstYear: '1982',
    crew: '2',
    armament: 'Dual-mounted 7.62mm swiveling machine guns',
    packagedWith: 'Clutch',
    bio: 'The G.I. Joe team’s original attack jeep, the V.A.M.P. was loosely based on the experimental Lamborghini Cheetah and became the workhorse vehicle of the earliest missions.',
    image: 'images/vamp.jpg'
  },
  {
    id: 'hiss-tank',
    name: 'H.I.S.S. Tank',
    fullName: 'High-Speed Sentry',
    affiliation: 'Cobra',
    vehicleType: 'Tank',
    firstYear: '1983',
    crew: '1 pilot + 2 riders',
    armament: 'Dorsal-mounted twin 30mm automatic cannons',
    packagedWith: 'Cobra Officer',
    bio: 'Cobra’s signature armored vehicle, the low-slung H.I.S.S. Tank became as visually iconic to Cobra as the VAMP was to the Joes, built for fast strikes on any terrain.',
    image: 'images/hisstank.jpg'
  },
  {
    id: 'skystriker',
    name: 'Skystriker XP-14F',
    fullName: 'Skystriker XP-14F Combat Jet',
    affiliation: 'G.I. Joe',
    vehicleType: 'Fighter Jet',
    firstYear: '1983',
    crew: '2 (often flown with one seat empty)',
    armament: 'Sidewinder, Sparrow, and Phoenix missiles; Vulcan Gatling cannon',
    packagedWith: 'Ace',
    bio: 'The Joe team’s primary air-superiority fighter, the Skystriker gave the team its own answer to Cobra’s growing air power, flown most famously by Ace.',
    image: 'images/skystriker.jpg'
  },
  {
    id: 'rattler',
    name: 'Rattler',
    fullName: 'Rattler Ground Attack Jet',
    affiliation: 'Cobra',
    vehicleType: 'Attack Jet',
    firstYear: '1984',
    crew: '1',
    armament: 'Nose-mounted 30mm anti-tank gun, turret-mounted 20mm twin guns, external hardpoints for bombs and missiles',
    packagedWith: 'Wild Weasel',
    bio: 'A heavily armed ground-attack aircraft, the Rattler lets Cobra bring overwhelming firepower to bear on entrenched positions, piloted most notably by Wild Weasel.',
    image: 'images/rattler.jpg'
  },
  {
    id: 'wolverine',
    name: 'Wolverine',
    fullName: 'Wolverine Armored Missile Vehicle',
    affiliation: 'G.I. Joe',
    vehicleType: 'Missile Vehicle',
    firstYear: '1983',
    crew: '1',
    armament: 'Twin missile launchers',
    packagedWith: 'Cover Girl',
    bio: 'A fast, lightly armored missile platform, the Wolverine is best known as Cover Girl’s signature vehicle, built for hit-and-run anti-armor strikes.',
    image: 'images/wolverine.jpg'
  },
  {
    id: 'mobat',
    name: 'M.O.B.A.T.',
    fullName: 'Motorized Battle Tank',
    affiliation: 'G.I. Joe',
    vehicleType: 'Tank',
    firstYear: '1982',
    crew: null,
    armament: '130mm anti-armor cannon, .50 caliber machine gun',
    packagedWith: 'Steeler',
    bio: 'The Joe team’s original main battle tank, the MOBAT gave the earliest missions serious armored firepower, piloted most famously by Steeler.',
    image: 'images/mobat.jpg'
  },
  {
    id: 'dragonfly',
    name: 'Dragonfly XH-1',
    fullName: 'Dragonfly XH-1 Assault Copter',
    affiliation: 'G.I. Joe',
    vehicleType: 'Helicopter',
    firstYear: '1983',
    crew: '2',
    armament: 'Sidewinder missiles, 25mm Vulcan chain gun, laser-guided 160mm cannon pod, mini-cannons, grenade launcher',
    packagedWith: 'Wild Bill',
    bio: 'A heavily armed assault helicopter, the Dragonfly is Wild Bill’s signature ride, built to deliver overwhelming firepower from the air.',
    image: 'images/dragonfly.jpg'
  },
  {
    id: 'mauler',
    name: 'Mauler M.B.T.',
    fullName: 'Mauler Manned Battle Tank',
    affiliation: 'G.I. Joe',
    vehicleType: 'Tank',
    firstYear: '1985',
    crew: null,
    armament: null,
    packagedWith: 'Heavy Metal',
    bio: 'Modeled after the real-world HSTV(L) prototype light tank, the Mauler upgraded the Joe team’s armor division, driven by Heavy Metal.',
    image: 'images/maulermbt.jpg'
  },
  {
    id: 'tomahawk',
    name: 'Tomahawk',
    fullName: 'CH-42 Tomahawk Heavy Transport Helicopter',
    affiliation: 'G.I. Joe',
    vehicleType: 'Helicopter',
    firstYear: '1986',
    crew: '2 (pilot + copilot), plus up to 7 passengers/gunners',
    armament: 'Twin .50 caliber machine guns, 20mm cannon, free-fall bombs, anti-obstacle missiles',
    packagedWith: null,
    bio: 'A heavy-lift transport helicopter modeled on the real-world Chinook, the Tomahawk moves troops and cargo while carrying enough armament to fight its way in and out, flown by Lift-Ticket.',
    image: 'images/tomahawk.jpg'
  },
  {
    id: 'water-moccasin',
    name: 'Water Moccasin',
    fullName: 'Cobra Water Moccasin',
    affiliation: 'Cobra',
    vehicleType: 'Attack Boat',
    firstYear: '1984',
    crew: null,
    armament: 'Depth charge',
    packagedWith: 'Copperhead',
    bio: 'Cobra’s answer to the Joes’ amphibious vehicles, the Water Moccasin lets Copperhead strike from swamps and waterways other forces avoid.',
    image: 'images/watermoccasin.jpg'
  },
  {
    id: 'sharc',
    name: 'S.H.A.R.C.',
    fullName: 'Submersible High-speed Attack Reconnaissance Craft',
    affiliation: 'G.I. Joe',
    vehicleType: 'Submersible',
    firstYear: '1984',
    crew: null,
    armament: null,
    packagedWith: 'Deep Six',
    bio: 'A flying submarine straddling the line between plausible and pure toy-line fantasy, the S.H.A.R.C. is Deep Six’s signature underwater reconnaissance craft.',
    image: 'images/sharc.jpg'
  },
  {
    id: 'whale',
    name: 'Killer W.H.A.L.E.',
    fullName: 'Warrior Hovering Assault Launching Envoy',
    affiliation: 'G.I. Joe',
    vehicleType: 'Hovercraft',
    firstYear: '1984',
    crew: '4 (pilot, navigator/gunner, 2 turret gunners) + 4-man insertion team',
    armament: 'Twin .50 caliber AA machine guns, twin 105mm cannons, quad-SAM launchers, depth charges',
    packagedWith: 'Cutter',
    bio: 'A massive amphibious hovercraft capable of carrying a full insertion team, the Killer W.H.A.L.E. is Cutter’s command vehicle and one of the largest Joe vehicles in the line.',
    image: 'images/killerwhale.jpg'
  },
  {
    id: 'awe-striker',
    name: 'A.W.E. Striker',
    fullName: 'All-Weather Attack Vehicle',
    affiliation: 'G.I. Joe',
    vehicleType: 'Attack Vehicle',
    firstYear: '1985',
    crew: '4',
    armament: 'Cage-mounted 70mm grenade launcher with onboard targeting camera',
    packagedWith: 'Crankcase',
    bio: 'A fast, rugged all-terrain vehicle built for reconnaissance and grenade-launcher support, the A.W.E. Striker is driven by Crankcase.',
    image: 'images/awestriker.jpg'
  },
  {
    id: 'thunder-machine',
    name: 'Thunder Machine',
    fullName: 'Dreadnok Thunder Machine',
    affiliation: 'Dreadnoks',
    vehicleType: 'Jet-Powered Attack Vehicle',
    firstYear: '1986',
    crew: '1 driver + up to 8 riding on the running boards',
    armament: 'Belt-fed synchronized "Penetrator" Gatling guns',
    packagedWith: 'Thrasher',
    bio: 'A jet-engine-powered four-wheeled monster cobbled together from salvaged parts and old tank armor, the Thunder Machine is Thrasher’s signature ride and the Dreadnoks’ most iconic vehicle.',
    image: 'images/thundermachine.jpg'
  },
  {
    id: 'dreadnok-cycle',
    name: 'Dreadnok Cycle',
    affiliation: 'Dreadnoks',
    vehicleType: 'Motorcycle',
    firstYear: '1987',
    crew: '1',
    armament: 'Removable missiles',
    packagedWith: null,
    bio: 'A rugged motorcycle built for the Dreadnoks’ hit-and-run style, the Dreadnok Cycle lets the gang’s riders scatter fast and strike faster.',
    image: 'images/dreadnokcycle.jpg'
  },
  {
    id: 'dreadnok-air-assault',
    name: 'Dreadnok Air Assault',
    affiliation: 'Dreadnoks',
    vehicleType: 'Aircraft Set (Gyrocopter + VTOL)',
    firstYear: '1986',
    crew: null,
    armament: 'Gyrocopter missiles and bomb; VTOL removable rockets',
    packagedWith: null,
    bio: 'A Sears-exclusive two-vehicle set pairing a gyrocopter with a VTOL aircraft, the Dreadnok Air Assault gives the gang an airborne strike option to match their ground vehicles.',
    image: 'images/dreadnokairassault.jpg'
  },
  {
    id: 'dreadnok-ground-assault',
    name: 'Dreadnok Ground Assault',
    affiliation: 'Dreadnoks',
    vehicleType: '4WD Vehicle + Motorcycle Set',
    firstYear: '1986',
    crew: null,
    armament: null,
    packagedWith: null,
    bio: 'A Sears-exclusive set pairing a 4WD assault jeep with a motorcycle, the Dreadnok Ground Assault gave the gang matching wheeled firepower for the ground game.',
    image: 'images/dreadnokgroundassault.jpg'
  },
  {
    id: 'chameleon-swamp-skier',
    name: 'Chameleon',
    fullName: 'Zartan’s Swamp Skier',
    affiliation: 'Dreadnoks',
    vehicleType: 'Swamp Skier',
    firstYear: '1984',
    crew: '1',
    armament: null,
    packagedWith: 'Zartan',
    bio: 'Zartan’s personal swamp skier, the Chameleon lets the master of disguise vanish into marshland and waterways where wheeled vehicles can’t follow.',
    image: 'images/chameleon.jpg'
  },
  {
    id: 'conquest-x30',
    name: 'Conquest X-30',
    affiliation: 'G.I. Joe',
    vehicleType: 'Combat Aircraft',
    firstYear: '1986',
    crew: '1',
    armament: 'Two heavy missiles, four light missiles',
    packagedWith: 'Slip-Stream',
    bio: 'A sleek experimental fighter released alongside the Joe team’s fifth toy series, the Conquest X-30 is Slip-Stream’s signature aircraft, built for high-speed strikes.',
    designer: 'Guy Cassaday — his first vehicle design for the line (1986)',
    image: 'images/conquest.jpg'
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    affiliation: 'G.I. Joe',
    vehicleType: 'Snow Tank',
    firstYear: '1990',
    crew: '1',
    armament: 'Laser cannon, heavy artillery',
    packagedWith: 'Cold Front',
    bio: 'An armored snow tank built for arctic combat, the Avalanche is driven by Cold Front and can shrug off terrain that would strand a wheeled vehicle.',
    image: 'images/avalanche1.jpg'
  },
  {
    id: 'cobra-hammerhead',
    name: 'Cobra Hammerhead',
    affiliation: 'Cobra',
    vehicleType: 'Submersible Assault Carrier',
    firstYear: '1990',
    crew: null,
    armament: null,
    packagedWith: 'Decimator',
    bio: 'A modular oceanic assault carrier that deploys sea sleds and one-man submarines, the Hammerhead lets Decimator strike from beneath the waves.',
    designer: 'Guy Cassaday — 1990 Hammerhead',
    image: 'images/cobrahammerhead.jpg'
  },
  {
    id: 'cobra-hurricane-vtol',
    name: 'Hurricane VTOL',
    fullName: 'Cobra Hurricane VTOL',
    affiliation: 'Cobra',
    vehicleType: 'VTOL Fighter',
    firstYear: '1990',
    crew: '1',
    armament: 'Weapons linked to a laser heads-up-display targeting system',
    packagedWith: 'Vapor',
    bio: 'A vertical-takeoff tactical fighter with swiveling engines, the Hurricane VTOL lets Vapor launch strikes from almost any terrain.',
    image: 'images/hurricanvtol.jpg'
  },
  {
    id: 'overlords-dictator',
    name: 'Dictator',
    fullName: 'Cobra Overlord’s Dictator',
    affiliation: 'Cobra',
    vehicleType: 'Heavy Tank',
    firstYear: '1990',
    crew: null,
    armament: null,
    packagedWith: 'Overlord',
    bio: 'A massive command tank built for Overlord’s bid to seize control of Cobra, the Dictator is as much a statement of power as it is a weapon.',
    image: 'images/dictator.jpg'
  },
  {
    id: 'rolling-thunder',
    name: 'Rolling Thunder',
    affiliation: 'G.I. Joe',
    vehicleType: 'Heavy Assault Vehicle',
    firstYear: '1988',
    crew: '1',
    armament: 'Cannon turret, chain-gun turret, 15-missile rocket gantry, four wing guns, roof gun, 12 cluster bombs',
    packagedWith: 'Armadillo',
    bio: 'One of the most heavily armed vehicles the Joe team ever fielded, the Rolling Thunder is driven by Armadillo and stacks cannons, missiles, and gun turrets onto a single armored chassis.',
    designer: 'Guy Cassaday — 1988 Rolling Thunder, which earned him the nickname "The King of the big vehicles"',
    image: 'images/rollingthunder.jpg'
  },
  {
    id: 'mudfighter',
    name: 'Mudfighter',
    affiliation: 'G.I. Joe',
    vehicleType: 'Low-Altitude Attack Aircraft',
    firstYear: '1989',
    crew: '1',
    armament: 'Two bomb racks, 16 bombs',
    packagedWith: 'Dogfight',
    bio: 'A low-flying bomber built for close air support, the Mudfighter lets Dogfight clear a path for pinned-down ground troops with a heavy bomb load.',
    image: 'images/mudfighter.jpg'
  },
  {
    id: 'arctic-blast',
    name: 'Arctic Blast',
    affiliation: 'G.I. Joe',
    vehicleType: 'Snow Vehicle',
    firstYear: '1989',
    crew: '1',
    armament: null,
    packagedWith: 'Windchill',
    bio: 'A rugged snow vehicle built to keep moving where wheeled transport fails, the Arctic Blast is Windchill’s ride into the coldest combat zones.',
    image: 'images/articblast.jpg'
  },
  {
    id: 'retaliator',
    name: 'Retaliator',
    affiliation: 'G.I. Joe',
    vehicleType: 'Rescue Helicopter',
    firstYear: '1990',
    crew: '1',
    armament: 'Capture claw, rescue winch',
    packagedWith: 'Updraft',
    bio: 'A rescue-focused helicopter built with input from champion pilot Updraft, the Retaliator uses a capture claw and winch to pull Joes out of hot zones rather than relying on weapons.',
    image: 'images/retaliator.jpg'
  },
  {
    id: 'cobra-mamba',
    name: 'Mamba',
    fullName: 'Cobra Mamba',
    affiliation: 'Cobra',
    vehicleType: 'Twin-Rotor Attack Helicopter',
    firstYear: '1987',
    crew: '1',
    armament: 'Detachable flight pods',
    packagedWith: 'Gyro-Viper',
    bio: 'A nimble twin-rotor attack helicopter with detachable flight pods, the Mamba gives Gyro-Viper close air support wherever Cobra needs it.',
    image: 'images/mamba.jpg'
  },
  {
    id: 'cobra-wolf',
    name: 'W.O.L.F.',
    fullName: 'Cobra W.O.L.F. (Winter Operational Light Fighting vehicle)',
    affiliation: 'Cobra',
    vehicleType: 'Winterized Attack Vehicle',
    firstYear: '1987',
    crew: '1',
    armament: null,
    packagedWith: 'Ice-Viper',
    bio: 'A winterized light attack vehicle, the W.O.L.F. gives Ice-Viper the speed and cold-weather durability to strike where standard Cobra vehicles can’t follow.',
    image: 'images/wolf.jpg'
  },
  {
    id: 'cobra-sea-ray',
    name: 'Sea Ray',
    fullName: 'Cobra Sea Ray',
    affiliation: 'Cobra',
    vehicleType: 'Multi-Mode Attack Craft',
    firstYear: '1987',
    crew: '1',
    armament: null,
    packagedWith: 'Sea Slug',
    bio: 'A shapeshifting attack craft that transitions between aircraft, submarine, and glider modes, the Sea Ray is Sea Slug’s vehicle for Cobra’s underwater operations.',
    image: 'images/searay.jpg'
  },
  {
    id: 'cobra-maggot',
    name: 'Maggot',
    fullName: 'Cobra Maggot',
    affiliation: 'Cobra',
    vehicleType: 'Tunneling Attack Vehicle',
    firstYear: '1987',
    crew: '1',
    armament: 'Gun emplacement',
    packagedWith: 'W.O.R.M.S.',
    bio: 'A tunneling attack vehicle that doubles as a mobile gun emplacement, the Maggot lets W.O.R.M.S. troopers strike from beneath the battlefield.',
    image: 'images/maggot.jpg'
  },
  {
    id: 'cobra-hiss-ii',
    name: 'H.I.S.S. II',
    fullName: 'Cobra H.I.S.S. II',
    affiliation: 'Cobra',
    vehicleType: 'Tank',
    firstYear: '1989',
    crew: '1 driver + 4-man sabotage team',
    armament: 'Rotating triple-gun turret, searchlight, two side guns, two missiles',
    packagedWith: 'Track-Viper',
    bio: 'An upgraded H.I.S.S. tank built to deliver a four-man sabotage team behind enemy lines, the H.I.S.S. II is driven by Track-Viper and hits harder than the original.',
    image: 'images/hiss2.jpg'
  },
  {
    id: 'cobra-condor-z25',
    name: 'Condor Z-25',
    fullName: 'Cobra Condor Z-25',
    affiliation: 'Cobra',
    vehicleType: 'High-Altitude Bomber',
    firstYear: '1989',
    crew: '1',
    armament: 'Ring gun, 4 missiles, 7 rotary bombs, 14 wing bombs',
    packagedWith: 'Aero-Viper',
    bio: 'A forward-swept-wing stealth bomber piloted by Aero-Viper, the Condor Z-25 is one of Cobra’s most advanced high-altitude strike aircraft.',
    image: 'images/cobracondor.jpg'
  },
  {
    id: 'badger',
    name: 'Badger',
    affiliation: 'G.I. Joe',
    vehicleType: 'Lead Assault Jeep',
    firstYear: '1991',
    crew: null,
    armament: 'Spring-action missile launch system, 3 missiles',
    packagedWith: null,
    bio: 'A fast, maneuverable assault jeep, the Badger pairs speed with concentrated battlefield firepower for quick strikes.',
    image: 'images/badger.jpg'
  },
  {
    id: 'cobra-ice-sabre',
    name: 'Ice Sabre',
    fullName: 'Cobra Ice Sabre',
    affiliation: 'Cobra',
    vehicleType: 'Arctic Assault Vehicle',
    firstYear: '1991',
    crew: '3',
    armament: 'Spring-loaded 2-port missile launcher (4 missiles), twin pivoting laser cannons',
    packagedWith: null,
    bio: 'A three-seat arctic assault vehicle, the Ice Sabre lets Cobra bring concentrated firepower into frozen terrain the standard fleet can’t handle.',
    image: 'images/icesabre.jpg'
  },
  {
    id: 'barracuda',
    name: 'Barracuda',
    affiliation: 'G.I. Joe',
    vehicleType: 'One-Man Attack Submarine',
    firstYear: '1992',
    crew: '1',
    armament: 'Missiles',
    packagedWith: null,
    bio: 'A compact one-man attack submarine with real diving action, the Barracuda gives a single Joe operative independent underwater strike capability.',
    image: 'images/barracuda.jpg'
  },
  {
    id: 'cobra-liquidator',
    name: 'Liquidator',
    fullName: 'Cobra Liquidator A.T.F.',
    affiliation: 'Cobra',
    vehicleType: 'Jet',
    firstYear: '1992',
    crew: null,
    armament: 'Water gun',
    packagedWith: null,
    bio: 'A jet armed with a water-gun weapon system despite its box art showing Cobra Commander piloting it, the Liquidator was sold without any included figure.',
    image: 'images/liquidator.jpg'
  },
  {
    id: 'cobra-detonator',
    name: 'Detonator',
    fullName: 'Cobra Detonator',
    affiliation: 'Cobra',
    vehicleType: 'Demolition Vehicle',
    firstYear: '1993',
    crew: '1',
    armament: null,
    packagedWith: 'Nitro-Viper',
    bio: 'A vehicle built to deliver and detonate explosive ordnance, the Detonator gives Nitro-Viper mobile demolition capability on the battlefield.',
    image: 'images/detonator.jpg'
  },
  {
    id: 'manta-ray',
    name: 'Manta Ray',
    fullName: 'G.I. Joe Manta Ray',
    affiliation: 'G.I. Joe',
    vehicleType: 'Inflatable Watercraft',
    firstYear: '1994',
    crew: null,
    armament: 'Spring-loaded cannon with missile',
    packagedWith: null,
    bio: 'An inflatable raft-style watercraft, the Manta Ray gives the Joe team a lightweight, easily deployed option for shallow-water and coastal missions.',
    image: 'images/mantaray.jpg'
  },
  {
    id: 'razor-blade',
    name: 'Razor-Blade',
    fullName: null,
    affiliation: 'G.I. Joe',
    vehicleType: null,
    firstYear: '1994',
    crew: null,
    armament: null,
    packagedWith: null,
    bio: 'Though its box art depicted Flint at the controls, the Razor-Blade shipped without any included figure.',
    image: 'images/razorblade.jpg'
  },
  {
    id: 'blockbuster',
    name: 'Blockbuster',
    fullName: null,
    affiliation: 'G.I. Joe',
    vehicleType: null,
    firstYear: '1994',
    crew: null,
    armament: null,
    packagedWith: 'Windchill',
    bio: 'Part of the 1994 Battle Corps assortment, the Blockbuster was packaged with the figure Windchill.',
    image: 'images/blockbuster.jpg'
  },
  {
    id: 'vindicator',
    name: 'Vindicator',
    fullName: null,
    affiliation: 'G.I. Joe',
    vehicleType: 'Hovercraft',
    firstYear: '1987',
    crew: null,
    armament: null,
    packagedWith: 'Blaster',
    bio: 'Part of the Battle Force 2000 sub-team’s vehicle fleet, the Vindicator is an armed hovercraft that lets Blaster cross water and marshland where wheeled vehicles can’t follow.',
    image: 'images/vindicator.jpg'
  },
  {
    id: 'vector',
    name: 'Vector',
    fullName: null,
    affiliation: 'G.I. Joe',
    vehicleType: 'Jet',
    firstYear: '1987',
    crew: null,
    armament: null,
    packagedWith: 'Maverick',
    bio: 'A Battle Force 2000 jet capable of vertical takeoff and landing, the Vector gives Maverick air support in confined combat zones.',
    image: 'images/vector.jpg'
  },
  {
    id: 'battle-copter',
    name: 'Battle Copter',
    fullName: null,
    affiliation: 'Cobra',
    vehicleType: 'Attack Helicopter',
    firstYear: '1991',
    crew: null,
    armament: null,
    packagedWith: 'Interrogator',
    bio: 'Cobra’s dedicated attack helicopter, the Battle Copter carries Interrogator on close air-support and reconnaissance runs.',
    image: 'images/battlecopter.jpg'
  },
  {
    id: 'persuader',
    name: 'Persuader',
    fullName: null,
    affiliation: 'G.I. Joe',
    vehicleType: 'Tank',
    firstYear: '1987',
    crew: null,
    armament: 'Two guns, six missiles',
    packagedWith: 'Back-Stop',
    bio: 'A ten-wheeled tank built to repel armored assaults, the Persuader gives Back-Stop heavy tracked firepower on rough terrain.',
    designer: 'Guy Cassaday',
    image: 'images/persuader.jpg'
  },
  {
    id: 'defiant',
    name: 'Defiant',
    fullName: 'Defiant: Space Vehicle Launch Complex',
    affiliation: 'G.I. Joe',
    vehicleType: 'Space Launch Complex',
    firstYear: '1987',
    crew: null,
    armament: 'Revolving gun doors',
    packagedWith: 'Hardtop and Payload',
    bio: 'A sprawling booster, space station, and shuttle playset billed as three vehicles in one, Defiant lets the Joe team launch, crew, and defend its own orbital missions, with Hardtop driving the ground-support Crawler and Payload piloting the shuttle itself.',
    image: 'images/defiant.jpg'
  },
  {
    id: 'uss-flagg',
    name: 'U.S.S. Flagg',
    fullName: 'U.S.S. Flagg Aircraft Carrier',
    affiliation: 'G.I. Joe',
    vehicleType: 'Aircraft Carrier',
    firstYear: '1985',
    crew: null,
    armament: 'Twin anti-ship guns, swiveling missile launcher with six missiles',
    packagedWith: 'Keel-Haul',
    bio: 'The largest playset ever produced for the line, the U.S.S. Flagg is a full-scale aircraft carrier serving as the Joe team’s floating command center, launch deck, and home port for its naval and air fleet.',
    image: 'images/USSflagg.jpg'
  },
  {
    id: 'terror-drome',
    name: 'Terror Drome',
    fullName: 'Cobra Terror Drome',
    affiliation: 'Cobra',
    vehicleType: 'Headquarters Base',
    firstYear: '1985',
    crew: null,
    armament: 'Gun turrets',
    packagedWith: 'Firebat and A.V.A.C.',
    bio: 'A sprawling two-level Cobra headquarters bristling with gun turrets and control stations, the Terror Drome doubles as a mobile base with a built-in launch bay for the Firebat mini-jet.',
    image: 'images/terrordrome.jpg'
  },
  {
    id: 'firebat',
    name: 'Firebat',
    fullName: 'Firebat Interceptor Mini-Jet',
    affiliation: 'Cobra',
    vehicleType: 'Light Assault Jet',
    firstYear: '1985',
    crew: '1',
    armament: null,
    packagedWith: 'A.V.A.C.',
    bio: 'Little more than a seat strapped to a rocket engine, the stripped-down Firebat mini-jet launches straight from the Terror Drome’s silo and demands a highly skilled pilot to control at speed.',
    image: 'images/firebat.jpg'
  },
  {
    id: 'cobra-flight-pod',
    name: 'Cobra Flight Pod',
    fullName: 'Cobra Flight Pod ("Trubble Bubble")',
    affiliation: 'Cobra',
    vehicleType: 'Mini Aircraft',
    firstYear: '1985',
    crew: '1',
    armament: 'Two missiles, detachable engines, aerial mine',
    packagedWith: null,
    bio: 'A tiny, bubble-canopied one-man flyer, the Cobra Flight Pod packs detachable engines and a pair of missiles into a vehicle barely bigger than its pilot, making it one of the smallest aircraft ever issued to Cobra ranks.',
    designer: 'Ron Rudat — 1985 Cobra Flight Pod',
    image: 'images/cobraflightpod.jpg'
  }
];